version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    container_name: saas-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./infra/.env.example

  backend:
    build: ./backend
    container_name: saas-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.example
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: saas-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.example
    depends_on:
      - backend

volumes:
  db_data:
